[package]
name = "patina_pcd"
version.workspace = true
repository.workspace = true
license.workspace = true
edition.workspace = true
readme = "README.md"
description = "PCD (Platform Configuration Database) service support for components."
keywords.workspace = true
categories.workspace = true

[lints]
workspace = true

[dependencies]
mockall = { workspace = true, optional = true }
patina = { workspace = true, features = ["alloc"] }

[dev-dependencies]
env_logger = { workspace = true }
mockall = { workspace = true }
patina = { workspace = true, features = ["mockall"] }

[features]
mockall = ["dep:mockall", "std"]
std = []
# All non-std features to test in CI
ci_features = []
