# @file ci-workflow.yml
#
# A workflow that runs basic CI tests and Rust CI tests, triggered on a pull_request or push to
# main.
#
##
# Copyright (c) Microsoft Corporation.
# SPDX-License-Identifier: Apache-2.0
##
name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
      - "major"
      - "feature/**/*"
  pull_request:
    branches:
      - "main"
      - "major"
      - "feature/**/*"

jobs:
  ci_workflow:
    name: Run
    uses: OpenDevicePartnership/patina-devops/.github/workflows/CiWorkflow.yml@main
    with:
      mdbook-path: "docs"
    secrets: inherit
