# @file ci-workflow.yml
#
# A workflow that runs basic CI tests and Rust CI tests, triggered on a pull_request or push to
# main.
#
##
# Copyright (c) Microsoft Corporation.
# SPDX-License-Identifier: Apache-2.0
##
name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
      - "major"
      - "feature/**/*"
  pull_request:
    branches:
      - "main"
      - "major"
      - "feature/**/*"

jobs:
  ci_workflow:
    name: Run
    uses: OpenDevicePartnership/patina-devops/.github/workflows/CiWorkflow.yml@v0.0.2
    with:
      build-tasks: "build,build-x64,build-aarch64"
      mdbook-path: "docs"
      run-cargo-vet: true
      run-release-dry-run: ${{ !contains(github.event.pull_request.body, '(skip cargo release dry run)') }}
    secrets: inherit
